.TH MYSTRCAT 3 "2025-09-23" "v0.4.1-final" "My Project Functions"
.SH NAME
mystrcat \- append source string to destination
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.P
int mystrcat(char* dest, const char* src);
.SH DESCRIPTION
Appends src string at the end of dest. Returns the total length of the new string.
.SH AUTHOR
Abdullah Rao <your_email@example.com>
