.TH MYSTRNCPY 3 "2025-09-23" "BCSF22M520-OS-A01" "Client Library Functions"
.SH NAME
mystrncpy \- copy up to n characters of a string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.P
int mystrncpy(char* dest, const char* src, int n);
.SH DESCRIPTION
Copies at most n characters from src to dest. Returns the number of characters copied.
.SH AUTHOR
Abdullah Rao <bcsf22m520@pucit.edu.pk>
