.TH MYSTRLEN 3 "2025-09-23" "BCSF22M520-OS-A01" "Client Library Functions"
.SH NAME
mystrlen \- compute the length of a string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.P
int mystrlen(const char* s);
.SH DESCRIPTION
Returns the number of characters in the string pointed to by s.
.SH AUTHOR
Abdullah Rao <bcsf22m520@pucit.edu.pk>
